app2/urls.py
from django.urls import path
app_name='app2'
from app2 import views
urlpatterns=[
    path('hello/',views.hello,name='hello')
]

project1/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',views.hai,name='hai'),
    path('bye/',views.bye,name='bye'),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')


def bye(request):
    return render(request,'bye.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    return render(request,'hello.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bye file</title>
</head>
<body>
    <h1>this is bye file</h1>
    <h1><a href="{% url 'hai' %}">go to hai file</a></h1>
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hai file</title>
</head>
<body>
    <h1>this is hai file</h1>
    <h1><a href="{% url 'bye' %}">go to bye file</a></h1>
    <h1><a href="{% url 'app2:hello' %}">go to hello file</a></h1>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hello file</title>
</head>
<body>
    <h1>this is hello file</h1>
    <h1><a href="{% url 'bye' %}">go to bye file</a></h1>
</body>
</html>